### ISSUE TITLE
MATLAB scripted plug-ins might not work

### ISSUE THREAD

**Issue by bcolombet** [anywave/anywave#3]
It appears that if AnyWave is installed on a path containing spaces, MATLAB will fail to find required mex functions to communicate with AnyWave.
For example, on Windows, if AnyWave is installed in C:\program files\AnyWave  you will get the issue.

This will be fixed soon. In the meanwhile, try to install or copy the AnyWave directory to a path that does not contain any spaces. For example C:\AnyWave.

**Comment by maedoc** [comment]
It's probably because the command form of `addpath` is used in the [MATLAB support](https://github.com/anywave/anywave/blob/master/src/MatlabSupport/AwMatlabSupport.cpp#L104)

```c++
command = "addpath " + awPath.absolutePath();
```

wheres spaces in the path result in multiple arguments to addpath, whereas

```c++
command = "addpath('" + awPath.absolutePath() + "')";
```

a space is considered as part of the path.

**Comment by bcolombet** [comment]
The path issue has been fixed in March 2015 release.
