### ISSUE TITLE
anywave does not work in debian 8

### ISSUE THREAD

**Issue by timpx** [anywave/anywave#31]
when starting anywave, I get the following error:

```
/usr/local/Anywave/AnyWaveLinux: /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/bin/glnxa64/libtiff.so.5: no version information available (required by /usr/lib/libvtkIO.so.5.8)
Segmentation fault
```
libtiff5 is installed, I also tried reinstalling and compiling myself anywave with different $MATLAB_ROOT env variables. The same error always shows up.

**Comment by maedoc** [comment]
http://stackoverflow.com/questions/25105971/calling-pdftops-does-not-work-in-matlab

**Comment by timpx** [comment]
I moved libtiff.so.5 to libtiff.so.5.bak, now I only got the segmentation fault.
Is there anyway to have a more detailed log?

**Comment by maedoc** [comment]
Try compiling Anywave in Debug:
```bash
cd build/
cmake .. -DCMAKE_BUILD_TYPE=Debug
...
gdb anywave
run
```

**Comment by timpx** [comment]
sorry my phone has a 35s battery.
compilation fails with  fatal error: hdf5.h: Aucun fichier ou dossier de ce type
I have already installed libhdf5-dev

**Comment by maedoc** [comment]
Compilation here on Debian 8 went just fine, and AnyWave opens without problems. I haven't installed the MCR, so maybe that's where the segfault is coming from. I'll try that next.

On fresh install, I did the following

```bash
su -c 'apt-get install git cmake build-essential libfftw3-dev libhdf5-dev liblapack-dev libopenblas-dev libqwt-dev libvtk5-qt4-dev'
git clone https://github.com/anywave/anywave
mkdir anywave/build
cd anywave/build
cmake ..
make -j2
```

and poof! I have AnyWave on Debian 8.

**Comment by bcolombet** [comment]
Thanks for testing on Debian 8 as I only have Debian 7 in my virtual machine.

If you don't need MATLAB support, do as maedoc suggested. MATLAB is hell on earth when dealing with shared libraries. MATLAB embeds some libs that are older than the ones present in the system, and cause conflicts.

Also, to launch Anywave without MATLAB environment variables, juste execute AnyWaveLinux binary file not the Anywave.sh shell script.

**Comment by maedoc** [comment]
After installing MCR on Deb 8 and running bin/AnyWaveLinux, I see that AW detects the MCR, but I don't have a segmentation fault.

**Comment by bcolombet** [comment]
AnyWave only supports MCR 8.0 (MATLAB R2012b) and the MCR is only required for MATLAB Compiled plug-ins.

**Comment by timpx** [comment]
I tried again at home, it appears first to make cmake works without giving errors I had to install libvtk-java, then the cmake and build worked fine, but again segfault (I am  not using Matlab support); I wonder if it comes from the fact that I updated debian 8 from debian 7. Anyway when using gdb I got the following:

```
(gdb) run
Starting program: /home/tim/Work/Soft/Anywave/anywave/build/bin/AnyWaveLinux 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffda06e700 (LWP 29629)]
[New Thread 0x7fffd986d700 (LWP 29630)]
[New Thread 0x7fffd706c700 (LWP 29631)]
ICE default IO error handler doing an exit(), pid = 29625, errno = 0
[Thread 0x7fffda06e700 (LWP 29629) exited]
[Thread 0x7fffd706c700 (LWP 29631) exited]
[Thread 0x7fffd986d700 (LWP 29630) exited]
[Inferior 1 (process 29625) exited with code 01]
```

At work, it also segfaults, but with different error: 
```
(gdb) run
Starting program: /home/tim/Work/Soft/Anywave/anywave/build/bin/AnyWaveLinux 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffda099700 (LWP 27541)]
[New Thread 0x7fffd9898700 (LWP 27542)]
[New Thread 0x7fffd7097700 (LWP 27543)]
"layout 'neuromag306eeg1005_natmeg' has 128 sensors." 
"layout 'yokogawa440_old' has 440 sensors." 
....
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff643d240 in QObject::staticMetaObject ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
```

 but there I'm trying via ssh -X, that may play a role.

**Comment by bcolombet** [comment]
Could you try using AnyWave directly on your computer to validate the ssh -X possible issue?

**Comment by timpx** [comment]
Yep, I just did that, still does not work...

**Comment by maedoc** [comment]
You may need to delete `~/.ICEauthority` file (it will be recreated) to resolve the ICE problem.

In general, upgrading Linuces is better done by installing the new version, to avoid library issues. This is why "advanced" users use separate partitions for `/home` and `/` so that you can reinstall without touching your data (I don't do this, but Debian installer does offer the option).

Given that AnyWave can be built and run on a fresh Debian 8 with MCR 8.1 installed, I think this is more likely a bug in your Linux installation.

**Comment by timpx** [comment]
I'll try tonight; I have separate partitions, but the ```apt-get upgrade``` system looked so nice... Usually a lot of updates are coming after a new release, I hope there will be fix for me inside... But you're right, I definitely think it's a library conflict somewhere.

**Comment by timpx** [comment]
ok now it works at home, deleting the  ```~/.ICEauthority``` file was the right call. Thanks!

**Comment by timpx** [comment]
still not working at work. Additional details with gdb:
```
(gdb) bt
#0  0x00007ffff643d240 in QObject::staticMetaObject ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#1  0x0000000000554bab in AwPluginManager::loadUserPlugins (
    this=this@entry=0xc048e0)
    at /home/tim/Work/Soft/Anywave/anywave/src/AnyWave/Plugin/AwPluginManager.cpp:348
#2  0x0000000000558549 in AwPluginManager::AwPluginManager (this=0xc048e0)
    at /home/tim/Work/Soft/Anywave/anywave/src/AnyWave/Plugin/AwPluginManager.cpp:80
#3  0x0000000000558715 in AwPluginManager::getInstance ()
    at /home/tim/Work/Soft/Anywave/anywave/src/AnyWave/Plugin/AwPluginManager.cpp:69
#4  0x0000000000583b14 in AnyWave::AnyWave (this=0x7fffffffd4b0, 
    parent=<optimized out>, flags=...)
    at /home/tim/Work/Soft/Anywave/anywave/src/AnyWave/AnyWave.cpp:144
#5  0x000000000047026a in main (argc=1, argv=0x7fffffffd7e8)
    at /home/tim/Work/Soft/Anywave/anywave/src/AnyWave/main.cpp:61
```
```

**Comment by bcolombet** [comment]
Remove all plugins in /home/user/AnyWave/Plugins

**Comment by timpx** [comment]
Bingo!! Thanks a lot, that works fine now!
