### ISSUE TITLE
Pragma errors building on Mac OS X 10.6.8

### ISSUE THREAD

**Issue by maedoc** [anywave/anywave#34]
The Micromed reader generates some errors during build:

```
.../micromedreader.h:83: error: too many #pragma options align=reset
```

**Comment by bcolombet** [comment]
Strange behavior as it was building correctly on 10.6 previously...

**Comment by maedoc** [comment]
Does Xcode use clang or g++ on 10.6?

**Comment by bcolombet** [comment]
Can you try to remove all #pragma directives?
There were used to align data in structs, but I modified the code to use QDataStream and align data manually. 
So, normally #pragma are not necessary anymore

**Comment by bcolombet** [comment]
Not using Xcode, but g++ directly.
CMake generates classic Makefiles.

g++ is an old version (4.2 I guess) but was building correctly before...

**Comment by maedoc** [comment]
hm I see there was a `#pragma pack(pop)` but no preceding push or whatever. Probably newer compilers are smart enough to ignore the pop.

Anyway, it compiles with that modification.
