### ISSUE TITLE
filters do not work on sEEG channels on debian

### ISSUE THREAD

**Issue by timpx** [anywave/anywave#39]

**Comment by bcolombet** [comment]
Please, can you send me the data file so I will able to debug the issue?

**Comment by timpx** [comment]
http://filez.univ-amu.fr/o9t3xnnuz8

**Comment by bcolombet** [comment]
Thanks.
Can you try to build again with the updated sources or try the new debian binary package?
I've built a debian 8 Jessie package that should install properly on your system.

You were right, a misnamed UI Widgets was preventing SEEG filters to be applied correctly.

**Comment by timpx** [comment]
I cannot compile anymore:
I did:
```
cd anywave
git pull
cd build
cmake ..
```
I get the error:
```
CMake Error at CMakeLists.txt:26 (add_subdirectory):
  add_subdirectory given source "src/Core-static" which is not an existing
  directory.
```

**Comment by bcolombet** [comment]
Sorry for that, I removed the Core-static. Should build.
Let me know

**Comment by timpx** [comment]
ok it works fine now, thanks
