### ISSUE TITLE
AnyWave will not open on Mac OS 10.7.5

### ISSUE THREAD

**Issue by dmgroppe** [anywave/anywave#4]
I successfully installed QT (http://meg.univ-amu.fr/AnyWave/qt-mac-opensource-4.8.5.dmg) and then installed AnyWave without error (http://meg.univ-amu.fr/AnyWave/AnyWave_maci64.zip). However, when I click on the AnyWave icon in my Applications folder, nothing happens. The "Anywave_Plugins" folder is also in my Applications folder. A friend of mine with a Mac is having the same problem.

**Comment by bcolombet** [comment]
The issue has been fixed since Feb 2015 version of AnyWave.
That was caused to dynamic libraries which were not found by AnyWave application.
The application is now built using static libraries.

**Comment by bcolombet** [comment]
Note that there is no need now to download and install Qt 4.8.5 on a Mac.
The installer package will install Qt Framework when installing AnyWave.
