### ISSUE TITLE
Markers UI opens when starting AnyWave

### ISSUE THREAD

**Issue by maedoc** [anywave/anywave#6]
The markers UI seems to automatically open whenever starting AnyWave, in the most recent version (Debian package on Ubuntu).

**Comment by bcolombet** [comment]
Yes that is right. In fact, the markers UI state is saved when closing AnyWave. Thus, if the user previously open the markers UI (when adding markers for example) and close AnyWave, the UI will reopen at next launch.

**Comment by bcolombet** [comment]
As a new ergonomic enhancement, the markers UI will open automatically when inserting markers.
It could be when the user click the little pencil button or when importing a marker file from the File menu.
